### ISSUE TITLE
Рамка дропзоны некрасивая

### ISSUE THREAD

**Issue by Steiden** [MrAbragadabra/fileslicker-frontend#11]
Я считаю, будет лучше, если расстояние между черточками рамки будет больше, а сами черточки длиннее

![image](https://github.com/user-attachments/assets/ee88b3eb-44d1-4418-9aff-fdfe4184f886)

**Comment by MrAbragadabra** [comment]
Началось душнение :3

**Comment by MrAbragadabra** [comment]
Я в понедельник попробую посмотреть, как будет лучше

**Comment by Steiden** [comment]
👌

> Я в понедельник попробую посмотреть, как будет лучше

**Comment by MrAbragadabra** [comment]
Мне и так нравится, так что всё, хы
